apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dgl8b1frk-dotnet-basic
  janus-idp.io/tekton: dgl8b1frk-dotnet-basic
  backstage.io/kubernetes-id: dgl8b1frk-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dgl8b1frk-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
